services:
  - type: web
    name: cme-tracker
    env: docker
    plan: standard
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cme_tracker.settings
      - key: OPENAI_API_KEY
        sync: false
