services:
  - type: web
    name: cme-tracker
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cme_tracker.settings
      - key: OPENAI_API_KEY
        sync: false  # Or provide the actual key here securely
