services:
  - type: web
    name: cme-tracker
    env: docker
    plan: standard  # <- this MUST be set if you've upgraded
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cme_tracker.settings
      - key: OPENAI_API_KEY
        sync: false
    startCommand: gunicorn cme_tracker.wsgi:application --timeout 120 --workers 1
