services:
  - type: web
    name: cme-tracker
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cme_tracker.settings
      - key: OPENAI_API_KEY
        sync: true  # Assumes you already have this in Render's dashboard
