services:
  - type: web
    name: cme-tracker
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn cme_tracker.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cme_tracker.settings
      - key: OPENAI_API_KEY
        sync: false
