services:
  - type: web
    name: cme-tracker
    env: python
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: gunicorn cme_tracker.wsgi:application --bind 0.0.0.0:10000 --timeout 120 --workers 1
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cme_tracker.settings
      - key: OPENAI_API_KEY
        sync: false
