services:
  - type: web
    name: cme-tracker
    env: python
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils tesseract-ocr
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn cme_tracker.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cme_tracker.settings

