# Generated by Django 5.2.4 on 2025-07-15 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CMERule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=2)),
                ("profession", models.CharField(max_length=100)),
                ("hours_required", models.PositiveIntegerField()),
                ("renewal_period", models.PositiveIntegerField()),
                (
                    "special_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("special_hours_required", models.FloatField(default=0.0)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CMEEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("hours", models.FloatField()),
                ("date_completed", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("opioid", "Opioid Education"),
                            ("ethics", "Ethics"),
                            ("bias", "Bias and Harassment"),
                            ("controlled", "Controlled Substances"),
                            ("pain", "Pain Management"),
                            ("suicide", "Suicide Prevention"),
                            ("child_abuse", "Child Abuse"),
                            ("public_health", "Public Health"),
                            ("medical_errors", "Medical Errors"),
                            ("general", "General"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="cme_pdfs/"),
                ),
                (
                    "certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="cme_certificates/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profession", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("license_number", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Expired", "Expired"),
                        ],
                        max_length=10,
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracker.cmerule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days_before", models.IntegerField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.medicallicense",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "license", "days_before")},
            },
        ),
    ]
