# Generated by Django 5.2.3 on 2025-07-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicallicense",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicallicense",
            name="profession",
            field=models.CharField(default="MD", max_length=50),
        ),
        migrations.AddField(
            model_name="medicallicense",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Expired", "Expired"),
                    ("Suspended", "Suspended"),
                    ("Revoked", "Revoked"),
                    ("Probation", "Probation"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="CMEEntry",
        ),
    ]
