# Generated by Django 5.2.3 on 2025-07-02 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tracker",
            "0002_medicallicense_issue_date_medicallicense_profession_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CMERule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profession", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=2)),
                ("hours_required", models.FloatField()),
                ("renewal_period_years", models.IntegerField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name="medicallicense",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.cmerule",
            ),
        ),
    ]
