# Generated by Django 5.2.3 on 2025-07-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_cmeentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cmerule",
            name="renewal_period_years",
        ),
        migrations.AddField(
            model_name="cmerule",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cmerule",
            name="period_years",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="cmerule",
            name="profession",
            field=models.CharField(max_length=20),
        ),
    ]
