# Generated by Django 5.2.3 on 2025-07-02 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_remove_cmerule_renewal_period_years_cmerule_notes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cmerule",
            old_name="period_years",
            new_name="renewal_period",
        ),
    ]
