# Generated by Django 5.2.3 on 2025-07-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_rename_period_years_cmerule_renewal_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmerule",
            name="special_requirements",
            field=models.TextField(blank=True, default=""),
        ),
    ]
