# Generated by Django 5.2.3 on 2025-07-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_cmerule_special_requirements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cmeentry",
            name="certificate",
        ),
        migrations.RemoveField(
            model_name="cmeentry",
            name="title",
        ),
        migrations.AddField(
            model_name="cmeentry",
            name="topic",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
