# Generated by Django 5.2.3 on 2025-07-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_remove_cmeentry_certificate_remove_cmeentry_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cmerule",
            old_name="hours_required",
            new_name="required_hours",
        ),
    ]
