# Generated by Django 5.2.3 on 2025-07-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_rename_hours_required_cmerule_required_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cmeentry",
            name="license",
        ),
        migrations.AlterField(
            model_name="cmeentry",
            name="topic",
            field=models.CharField(max_length=200),
        ),
    ]
