# Generated by Django 5.2.3 on 2025-07-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_remove_cmeentry_license_alter_cmeentry_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmeentry",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
