# Generated by Django 5.2.3 on 2025-07-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_cmeentry_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmerule",
            name="special_hours_required",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
