# Generated by Django 5.2.3 on 2025-07-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_cmerule_special_hours_required"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cmerule",
            name="special_requirements",
        ),
        migrations.AddField(
            model_name="cmerule",
            name="special_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("opioid", "Opioid Education"),
                    ("ethics", "Ethics"),
                    ("bias", "Bias and Harassment"),
                    ("controlled", "Controlled Substances"),
                    ("pain", "Pain Management"),
                    ("suicide", "Suicide Prevention"),
                    ("child_abuse", "Child Abuse"),
                    ("public_health", "Public Health"),
                    ("medical_errors", "Medical Errors"),
                    ("general", "General"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cmeentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("opioid", "Opioid Education"),
                    ("ethics", "Ethics"),
                    ("bias", "Bias and Harassment"),
                    ("controlled", "Controlled Substances"),
                    ("pain", "Pain Management"),
                    ("suicide", "Suicide Prevention"),
                    ("child_abuse", "Child Abuse"),
                    ("public_health", "Public Health"),
                    ("medical_errors", "Medical Errors"),
                    ("general", "General"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="cmerule",
            name="profession",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cmerule",
            name="renewal_period",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cmerule",
            name="special_hours_required",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
