# Generated by Django 5.2.3 on 2025-07-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0013_remove_cmerule_special_requirements_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cmerule",
            old_name="required_hours",
            new_name="hours_required",
        ),
        migrations.AlterField(
            model_name="cmeentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("opioid", "Opioid Education"),
                    ("ethics", "Ethics"),
                    ("bias", "Bias and Harassment"),
                    ("controlled", "Controlled Substances"),
                    ("pain", "Pain Management"),
                    ("suicide", "Suicide Prevention"),
                    ("child_abuse", "Child Abuse"),
                    ("public_health", "Public Health"),
                    ("medical_errors", "Medical Errors"),
                    ("general", "General"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="cmerule",
            name="profession",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="cmerule",
            name="special_hours_required",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="medicallicense",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medicallicense",
            name="profession",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="medicallicense",
            name="status",
            field=models.CharField(max_length=20),
        ),
    ]
