# Generated by Django 5.2.3 on 2025-07-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0014_rename_required_hours_cmerule_hours_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicallicense",
            name="renewal_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medicallicense",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Expired", "Expired"),
                ],
                max_length=10,
            ),
        ),
    ]
