# Generated by Django 5.2.3 on 2025-07-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0015_medicallicense_renewal_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicallicense",
            name="renewal_date",
        ),
        migrations.AddField(
            model_name="cmeentry",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="cme_pdfs/"),
        ),
    ]
