# Generated by Django 5.2.3 on 2025-07-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0016_remove_medicallicense_renewal_date_cmeentry_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmeentry",
            name="certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="cme_certificates/"
            ),
        ),
    ]
