# Generated by Django 5.2.3 on 2025-07-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0017_cmeentry_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmerule",
            name="hours_required",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="cmerule",
            name="profession",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="cmerule",
            name="renewal_period",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="cmerule",
            name="special_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="cmerule",
            unique_together={("state", "profession")},
        ),
    ]
