# Generated by Django 5.2.3 on 2025-07-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0018_alter_cmerule_hours_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicallicense",
            name="custom_renewal_period",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicallicense",
            name="custom_special_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("opioid", "Opioid Education"),
                    ("ethics", "Ethics"),
                    ("bias", "Bias and Harassment"),
                    ("controlled", "Controlled Substances"),
                    ("pain", "Pain Management"),
                    ("suicide", "Suicide Prevention"),
                    ("child_abuse", "Child Abuse"),
                    ("public_health", "Public Health"),
                    ("medical_errors", "Medical Errors"),
                    ("general", "General"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="medicallicense",
            name="custom_special_hours_required",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicallicense",
            name="custom_total_cme_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medicallicense",
            name="profession",
            field=models.CharField(default="MD", max_length=100),
        ),
    ]
